version: "3.3"

services:
  database:
    image: mariadb:10.5
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "openSIS"
      MYSQL_USER: "openSIS_rw"
      MYSQL_PASSWORD: "Op3nS!S"
    volumes:
      - db_data:/var/lib/mysql
      - ./MYSQL/mysql-config/strict_mode.cnf:/etc/mysql/conf.d/strict_mode.cnf
      - ./MYSQL/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - opensis_network

  opensis-ui:
    image: opensis-ui
    container_name: opensis-ui-container
    depends_on:
      - database
    ports:
      - "8080:80"
      - "80:80"
    networks:
      - opensis_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
      - $PWD/rules.yml:/etc/prometheus/rules.yml
    networks:
      - monitoring_network
    ports:
      - "9090:9090"
    depends_on:
      - opensis-ui

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - monitoring_network
    ports:
      - "9100:9100"

  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    volumes:
      - ./alertmanager.yml:/alertmanager/alertmanager.yml
    networks:
      - monitoring_network
    ports:
      - "9093:9093"

  grafana_postgres:
    container_name: grafana_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: grafana_db
      POSTGRES_USER: grafana_usr
      POSTGRES_PASSWORD: abc123  # Replace this with an actual password
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana_postgres
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_usr
      GF_DATABASE_PASSWORD: abc123  # Replace this with an actual password
      GF_SECURITY_ADMIN_USER: siresol
      GF_SECURITY_ADMIN_PASSWORD: Actuarial1  # Replace with a secure password
      
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring_network
    depends_on:
      - grafana_postgres

networks:
  opensis_network:
  monitoring_network:

volumes:
  db_data:
  grafana-storage:
  postgres-storage:
